export const mockRecipes = [
  {
    id: 1,
    title: 'Spaghetti Carbonara',
    ingredients: [
      '200g spaghetti',
      '100g pancetta',
      '2 large eggs',
      '50g pecorino cheese',
      '50g parmesan',
      '2 cloves of garlic',
      'Salt',
      'Black pepper',
    ],
    instructions: [
      'Cook the spaghetti in a large pot of boiling salted water until al dente.',
      'Fry the pancetta with the garlic until the pancetta is crispy.',
      'Beat the eggs in a bowl, then add the grated pecorino and parmesan cheese.',
      'Drain the spaghetti and add it to the pancetta. Remove from heat.',
      'Quickly mix in the egg and cheese mixture, stirring constantly to create a creamy sauce.',
      'Season with salt and black pepper to taste.',
      'Serve immediately.',
    ],
    prepTime: '10 mins',
    cookTime: '20 mins',
    servings: 2,
  },
  {
    id: 2,
    title: 'Chicken Curry',
    ingredients: [
      '500g chicken breast',
      '1 large onion',
      '2 cloves of garlic',
      '1 tbsp ginger paste',
      '2 tbsp curry powder',
      '400ml coconut milk',
      '1 can diced tomatoes',
      'Salt',
      'Pepper',
      'Fresh cilantro',
    ],
    instructions: [
      'Dice the chicken breast into bite-sized pieces.',
      'Chop the onion and garlic.',
      'In a large pot, sauté the onion, garlic, and ginger paste until fragrant.',
      'Add the chicken pieces and cook until browned.',
      'Stir in the curry powder and cook for another minute.',
      'Pour in the coconut milk and diced tomatoes. Bring to a simmer.',
      'Cook for 20-25 minutes until the chicken is cooked through.',
      'Season with salt and pepper to taste.',
      'Garnish with fresh cilantro before serving.',
    ],
    prepTime: '15 mins',
    cookTime: '30 mins',
    servings: 4,
  },
];

export const mockItems = [
  {
    name: 'Sample Item 1',
    icon: '',
    expiry: '2023-12-31T23:59:59.000Z',
    tags: ['tag1', 'tag2'],
    isFrozen: true,
    count: '10',
  },
  {
    name: 'Sample Item 2',
    icon: '',
    expiry: '2025-02-04T23:59:59.000Z',
    tags: ['tag3'],
    isFrozen: false,
    count: '3',
  },
];
